md_name: DeepMFC
net:
  _target_: core.deepMFC.DeepMFC
  nblk: 64

engine:
  # _target_: core.trainer.Trainer_AFC.Trainer
  _target_: core.trainer.Trainer_AFC.TrainerE2E
  woRef: True
  # train_batch_sz: 16
  # train_num_workers: 32
  # valid_batch_sz: 36
  # valid_num_workers: 36
  # vtest_batch_sz: 16
  # vtest_num_workers: 16
# predictor:
# _target_: core.Trainer_wGAN_for_fig6.PredictorVAD
