defaults:
  - _self_
  - dset: dns
  - loss: basic
  - model: afc
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

model:
  engine:
    _target_: core.trainer.Trainer_AFC.Trainer
    name: ${model.md_name}
    desc: ""
    info_dir: "${oc.env:HOME}/model_results_trunk/AFC/HS_rirs"
    resume: True
    optimizer_name: "adam"
    lr: 5e-4
    epochs: 25
    scheduler_name: "stepLR"
    step_size: 10
    gamma: 0.5
    fs: 16000
    valid_per_epoch: 1
    vtest_per_epoch: 1
    dsets_raw_metrics: "dset_metrics.json"
    ncol: 200

    train_batch_sz: 16
    train_num_workers: 32
    valid_batch_sz: 36
    valid_num_workers: 36
    vtest_batch_sz: 16
    vtest_num_workers: 16

    valid_first: ${valid_first}
    vtest_first: ${vtest_first}
    root_save_dir: ${root_save_dir}

    net: ${model.net}
    loss_list: ${loss}

    # net_D:
    #   _target_: core.rebuild.FTCRN.Discriminator
    #   ndf: 16

    train_dset: ${dset.train}
    valid_dset: ${dset.valid}
    vtest_dset: ${dset.vtest}
    vpred_dset: ${dset.vpred}
    # dset_collate_fn:
    # _target_: core.Trainer_wGAN_for_fig6.get_pad_func

  predictor:
    _target_: core.Trainer_wGAN_for_fig6.PredictorVAD
    name: ${model.md_name}
    net: ${model.net}
    ckpt: 25
    dset: ${dset.vtest}
    info_dir: ${model.engine.info_dir}
    fs: 16000
    root_save_dir: ${root_save_dir}

valid_first: False
vtest_first: False
root_save_dir:
# valid epoach
vep:

pred: False
