config:
  name: rnnoise
  name_vad: rnnoise_vad
  epochs: 300
  desc: config_vad
  info_dir: trained_vad
  resume: true
  optimizer: adam
  scheduler: stepLR
  valid_per_epoch: 1
  vtest_per_epoch: 0  # 0 for disabled
  # the output dir to store the predict files of `vtest_dset` during testing
  vtest_outdir: vtest
  dsets_raw_metrics: dset_metrics.json


dataset:
  train_dset: "D:\\datasets\\rnnoise_vad\\train_300"
  valid_dset: "D:\\datasets\\rnnoise_vad\\valid_3"
  vtest_dset:
