config:
  name: 'msa-dpcrn'
  epochs: 100
  desc: ''
  info_dir: 'trained_msadpcrn'
  resume: true
  optimizer: 'adam'
  scheduler: 'stepLR'
  valid_per_epoch: 1
  vtest_per_epoch: 5 # 0 for disabled
  ## the output dir to store the predict files of `vtest_dset` during testing
  vtest_outdir: 'vtest'
  dsets_raw_metrics: 'dset_metrics.json'

md_conf:
  nframe: 128
  nhop: 64
  nfft: 128
  cnn_num: [16,32,64]
  stride: [2,2,1]
  rnn_hidden_num: 64
