config:
  name: 'conformer_base_1'
  epochs: 100
  desc: ''
  info_dir: 'trained_ns_32w64'
  resume: true
  optimizer: 'adam'
  scheduler: 'stepLR'
  valid_per_epoch: 1
  vtest_per_epoch: 5 # 0 for disabled
  ## the output dir to store the predict files of `vtest_dset` during testing
  vtest_outdir: 'vtest'
  dsets_raw_metrics: 'dset_metrics.json'
  train_batch_sz: 4
  train_num_workers: 6
  valid_batch_sz: 2
  valid_num_workers: 4
  vtest_batch_sz: 2
  vtest_num_workers: 4

md_conf:
  nframe: 64
  nhop: 32
  mid_channel: 20
