defaults:
  - _self_
  - model: joint
  - dset: dns_challenge


model:
  engine:
    name: null
    epochs: 30
    desc: ""
    lr: 5e-4
    batch_size: 15
    info_dir: "~/model_results_trunk/FIG6/fig6_GAN"
    resume: True
    optimizer_name: "adam"
    scheduler_name: "stepLR"
    valid_per_epoch: 1
    vtest_per_epoch: 1
     dsets_raw_metrics: "dset_metrics.json"
    train_batch_sz: 3  # 6(48), 10 for ftcrn, 12
    train_num_workers: 16
    valid_batch_sz:  12
    valid_num_workers: 16
    vtest_batch_sz:  8
    vtest_num_workers: 16
