md_name: &name PrimeKNet
net:
  _target_: core.PrimeKNet.LKFCA_NetFIG6
  h:
    n_fft:  512
    hop_size: 256
    win_size: 512
    beta: 2.0
    dense_channel: 64

engine:
  name: *name
  _target_: core.Trainer_wGAN_for_fig6.TrainerforMPSENET
  train_batch_sz: 3
  valid_batch_sz: 6
  ncol: null

  net_D:
    _target_: core.MP_SENet.MetricDiscriminator
    dim: 16
