dset_name: libriDemand
#
train:
  _target_: core.utils.trunk_v2.FIG6Trunk
  dirname: '/home/deepni/datasets/dns_wdrc/libri_demand_train_100'
  flist: "fig6_libridemand_train.csv"
  pattern: '[!.]*_nearend.wav'
  keymap:
      - "nearend.wav"
      - "target.wav"
  nlen: 5.0
  min_len: 2.0
  # return_clean: True
  # vad: True
valid:
  _target_: core.utils.trunk_v2.FIG6Trunk
  # dirname: '/home/deepni/datasets/dns_wdrc/dns_testset_noverb'
  dirname: '/home/deepni/datasets/dns_wdrc/libri_demand_dev'
  # dirname: '/home/deepni/datasets/dns_wdrc/dev_vad'
  flist: "fig6_libridemand_valid.csv"
  # flist: "fig6_sig_dev_vad.csv"
  pattern: "**/[!.]*_nearend.wav"
  keymap:
      - "nearend.wav"
      - "target.wav"
  # vad: True
vtest:
  _target_: core.utils.trunk_v2.FIG6Trunk
  dirname: '/home/deepni/datasets/dns_wdrc/libri_demand_test'
  # dirname: '/home/deepni/datasets/dns_wdrc/dns_testset_noverb'
  # dirname: '/home/deepni/datasets/dns_wdrc/fig6_voicebank_train'
  pattern: "**/[!.]*_nearend.wav"
  flist: "fig6_libridemand_test.csv"
  keymap:
      - "nearend.wav"
      - "target.wav"
  # vad: True
